version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"  # FastAPI
    command: uvicorn main_pine:app --host 0.0.0.0 --port 8000
    networks:
      - fastapi_network

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8501:8501"  # Streamlit
    command: streamlit run streamlit.py --server.port 8501 --server.address 0.0.0.0
    networks:
      - fastapi_network

networks:
  fastapi_network:
    driver: bridge
